### ISSUE TITLE
How to get a the type T of a given a TypeDesc* ?

### ISSUE THREAD

**Issue by berdal84** [Grouflon/mirror#6]
I would like to get the type of a TypeDesc, for example something like that:
```cpp
int myVar = 0;
TypeDesc* t = mirror::TypeDescGetter<decltype(myVar)>().Get();
using T = mirror::TypeDescT(t)::type;
T myOtherVar = 1; // T must be int
```

**Comment by Grouflon** [comment]
Je crois pas que ce soit posible de faire ça. je vois pas trop comment à la compilation il pourrait connaitre le type qu'aura t sans éxécuter quoi que ce soit vu que TypeDesc c'est justement pas un template.

**Comment by berdal84** [comment]
Il faudrait voir comment std::variant est implémenté.

https://en.cppreference.com/w/cpp/utility/variant

On peut interroger le contenu, genre avec: std::get< T >(variant) ou std::get< size_t >(variant)

Y'a aussi: std::holds_alternative
 https://en.cppreference.com/w/cpp/utility/variant/holds_alternative

Ceci dit, le variant stocke une valeur et c'est un template.

**Comment by Grouflon** [comment]
Ça peut pas marcher à mon sens. Les types possibles du std::variant doivent être connus à l'avance. Ça a l'air d'être juste une union et un enum de types un peu fancy en vrai, mais il faut toujours connaitre l'intégralité des types à la déclaration

**Comment by Grouflon** [comment]
Une fois de plus, mirror c'est un framework runtime. Je pense pas que ça puisse avoir beaucoup d'utilité à la compilation.
Pour preuve, tes typedescs sont effectivement instanciés la première fois que t'appelle leur getter.
